name: Delete Project in SonarCloud
on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub Actions
jobs:
  delete-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Verify if the project exists in SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REPO_NAME: pet-clinic
          ORGANIZATION: glemosas
        run: |
          echo "Checking if the project $REPO_NAME exists in SonarCloud..."
          response=$(curl -s -w "%{http_code}" -o response.json -u "$SONAR_TOKEN:" \
            "https://sonarcloud.io/api/projects/search?organization=$ORGANIZATION&project=$REPO_NAME")

          http_code=$(echo "$response" | tail -n1)
          if [ "$http_code" -eq 200 ]; then
            project_exists=$(cat response.json | jq '.components | length')
            if [ "$project_exists" -gt 0 ]; then
              echo "Project found. Proceeding to delete..."
            else
              echo "Project not found. Exiting."
              exit 1
            fi
          else
            echo "Error while checking project existence. HTTP Response Code: $http_code"
            cat response.json
            exit 1
          fi
      - name: Delete the project in SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REPO_NAME: pet-clinic
          ORGANIZATION: glemosas
        run: |
          echo "Deleting the project $REPO_NAME in SonarCloud..."
          delete_response=$(curl -s -w "%{http_code}" -o delete_response.json -X POST -u "$SONAR_TOKEN:" \
            "https://sonarcloud.io/api/projects/delete" \
            -d "organization=$ORGANIZATION" \
            -d "project=$REPO_NAME")

          http_code=$(echo "$delete_response" | tail -n1)
          if [ "$http_code" -eq 200 ]; then
            echo "Project successfully deleted from SonarCloud."
          else
            echo "Error while deleting the project. HTTP Response Code: $http_code"
            cat delete_response.json
            exit 1
          fi
